apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-gw-route
  namespace: wso2-external-gw
spec:
  parentRefs:
    - name: wso2-gateway
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - "external-gw.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
      - group: gateway.envoyproxy.io
        kind: Backend
        name: external-gw-backend
        port: 8243
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: external-gw-backend
  namespace: wso2-external-gw
spec:
  type: Endpoints
  endpoints:
  - fqdn:
      hostname: apim-gw-wso2am-universal-gw-service.wso2-external-gw.svc.cluster.local
      port: 8243
  tls:
    insecureSkipVerify: true
